### ISSUE TITLE
BUG:Error during arguments converted during string formatting in db_worker.py module

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/sslv_web_scraper#162]
Debug info: Started dat_formater module ...
Debug info: Ended data_formater module ...
Debug info: Starting data frame cleaning module ...
Debug info: Completed dat_formater module ...
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/./app/main.py", line 15, in <module>
    from app.wsmodules.db_worker import db_worker_main
  File "/./app/wsmodules/db_worker.py", line 610, in <module>
    db_worker_main()
  File "/./app/wsmodules/db_worker.py", line 80, in db_worker_main
    save_text_to_file(removed_ads_text_data)
  File "/./app/wsmodules/db_worker.py", line 607, in save_text_to_file
    filehandle.writelines("%s\n" % line for line in text_lines)
  File "/./app/wsmodules/db_worker.py", line 607, in <genexpr>
    filehandle.writelines("%s\n" % line for line in text_lines)
TypeError: not all arguments converted during string formatting

**Comment by vfedotovs** [comment]
Closing as issue cannot be reproduced on demand
