### ISSUE TITLE
Fix bug FileNotFoundError: [Errno 2] No such file or directory: 'cleaned-sorted-df.csv'

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/sslv_web_scraper#23]
./db_worker.py
DEBUG: Satrting db_worker module ...
DEBUG: Loaded cleaned-sorted-df.csv to dataframe in memory ...
Traceback (most recent call last):
  File "./db_worker.py", line 145, in <module>
    db_worker_main()
  File "./db_worker.py", line 36, in db_worker_main
    df_hashes = get_data_frame_hashes('cleaned-sorted-df.csv')
  File "./db_worker.py", line 54, in get_data_frame_hashes
    df = pd.read_csv(df_filename)
  File "/Users/vfedotovs/Library/Python/3.8/lib/python/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/vfedotovs/Library/Python/3.8/lib/python/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/Users/vfedotovs/Library/Python/3.8/lib/python/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/Users/vfedotovs/Library/Python/3.8/lib/python/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/vfedotovs/Library/Python/3.8/lib/python/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'cleaned-sorted-df.csv'

**Comment by vfedotovs** [comment]
Resolved
