### ISSUE TITLE
BUG(ws):Docker container restarted with FileNotFoundError: [Errno 2] No such file or directory: 'cleaned-sorted-df.csv'

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/sslv_web_scraper#319]
Affected deploy: 20240922-1636-deploy
Affected version/commit: 6c48eac (dev-1.5.4) Merge PR #308 from vGH305-incomplete-email-body
Impact : DB was not updated backup file size did not increment

 
```sh
From ws docker contaner log
---
2024-10-31 00:52:03,468 [INFO ] : run_long_task: 103: Running db_worker_main task: using locally scraped file
INFO:fastapi:Running db_worker_main task: using locally scraped file
INFO:db_worker: --- Satrting db_worker module ---
INFO:db_worker:Checking if required module file cleaned-sorted-df.csv exits in /
ERROR:db_worker:There was an error opening the file cleaned-sorted-df.csv or file does not exist!
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/wsmodules/db_worker.py", line 109, in check_files
    file = open(file_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'cleaned-sorted-df.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
-- cut --
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 104, in run_long_task
    db_worker_main()
  File "/app/wsmodules/db_worker.py", line 59, in db_worker_main
    check_files(requred_files)
  File "/app/wsmodules/db_worker.py", line 115, in check_files
    sys.exit()
SystemExit
```

Triage is required way file was missing

**Comment by vfedotovs** [comment]
The FileNotFoundError in your traceback indicates that the db_worker module attempts to access cleaned-sorted-df.csv without checking if it exists, which results in an unhandled exception. When sys.exit() is called in response to this, it causes the entire application to terminate, leading to the container crash. Here’s how to improve this to prevent future crashes:

1. Implement Robust Error Handling
Catch File Errors Gracefully: Instead of terminating with sys.exit(), catch the FileNotFoundError and handle it more gracefully, such as by logging the error and skipping the task or providing a fallback mechanism.

Raise Custom Exceptions: Consider raising a custom exception within check_files and catching it higher up in the call stack to control the flow when the file is missing, avoiding a hard exit.

```py
# Improved error handling in check_files
def check_files(required_files):
    for file_name in required_files:
        try:
            with open(file_name, 'r') as file:
                # process file
                pass
        except FileNotFoundError as e:
            logging.error(f"File {file_name} not found: {e}")
            return False  # or handle in a way that doesn't crash the application
    return True

```
2. Remove or Modify sys.exit() Calls
Avoid calling sys.exit() in a non-CLI Python application, especially in modules that are called by an ASGI server like FastAPI. This function exits the Python interpreter, which in turn stops the entire container.
Instead, return a status or log an error, allowing the server to continue running without crashing.


3. Add a Healthcheck for Critical Files in Dockerfile or Entrypoint
Use a shell script or Python script to check for essential files before starting the application. If a required file is missing, handle it by logging an error and possibly pausing or notifying rather than starting the service.

```dockerfile
HEALTHCHECK CMD python3 -c "import os; exit(0 if os.path.exists('/cleaned-sorted-df.csv
```
