### ISSUE TITLE
BUG(ws): Web scrape is skipped for one day due to last downloaded cloud scraped data file is the same as day before 

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/sslv_web_scraper#340]
Affected deploy: 20241104-2315-deploy-ws 
Affected commit: 2c45809  branch (dev-1.5.8) 
Application impact: One day data does NOT get scraped and inserted in DB  

```sh
ls -l /tmp
total 396
user 134911 Nov 16 13:17 pg_backup_2024_11_16.sql
# Postgres DB backup is identical 2 days in row
user 134912 Nov 17 06:05 pg_backup_2024_11_17.sql. <<<<
user 134912 Nov 18 03:05 pg_backup_2024_11_18.sql. <<<<

Issue occoured before 
[ec2-user@ip-172-31-1-2 ~]$ date
Mon Nov 18 11:40:28 UTC 2024

df_changer.log:2024-11-15 01:16:35,384 [INFO ] : create_file_copy: 340: Completed moving file: pandas_df_2024-11-15.csv to folder 'data/' with success.File size: 10394 bytes
df_changer.log:2024-11-16 01:16:40,084 [INFO ] : create_file_copy: 340: Completed moving file: pandas_df_2024-11-16.csv to folder 'data/' with success.File size: 10587 bytes. <<<
df_changer.log:2024-11-17 01:16:44,935 [INFO ] : create_file_copy: 340: Completed moving file: pandas_df_2024-11-17.csv to folder 'data/' with success.File size: 10587 bytes   <<<


2024-11-17 01:16:44,880 [INFO ] file_downloader: move_file_to: 76: File Ogre-raw-data-report-2024-11-17T00-29-25.txt moved to local_lambda_raw_scraped_data/Ogre-raw-data-report-2024-11-17T00-29-25.txt

Root cause file_downloader downloads invalid file:
2024-11-18 01:16:49,449 [INFO ] file_downloader: get_last_file_name: 58: Getting last object from S3 buncked lambda-ogre-scraped-data
2024-11-18 01:16:49,608 [INFO ] file_downloader: get_last_file_name: 64: Found last S3 bucket object Ogre-raw-data-report-2024-11-17T00-29-25.txt   <<< NOT valid (should contain todays date 2024-11-18 in file name )
txt

--cut --
xt to lfn: //Ogre-raw-data-report-2024-11-17T00-29-25.txt from S3: lambda-ogre-scraped-data
2024-11-18 01:16:49,659 [INFO ] file_downloader: download_latest_lambda_file: 85: File Ogre-raw-data-report-2024-11-17T00-29-25.txt download was successful   <<<


```

**Comment by vfedotovs** [comment]
Root cause why backup file was duplicate and  was the same size pandas_df_2024-11-16.csv 
 
From web_scraper.log - traceback not visible  - needs fix
2024-11-20 01:17:13,573 [INFO ] web_scraper : remove_old_file: 115: The file Ogre-raw-data-report.txt does not exist in the current directory.
2024-11-22 01:17:30,775 [INFO ] web_scraper : scrape_website: 45: --- Starting web_scraper module ---
2024-11-22 01:17:30,775 [INFO ] web_scraper : scrape_website: 46: Extracting BS4 objects
2024-11-22 01:17:30,775 [INFO ] web_scraper : remove_old_file: 102: Removing file Ogre-raw-data-report.txt  as if oloder than 1  day(s) ???
--- cut --
Next ay request starts here:
2024-11-22 01:17:30,775 [INFO ] web_scraper : remove_old_file: 115: The file Ogre-raw-data-report.txt does not exist in the current directory.


From docker logs af79c564c834 Traceback can be seen due to 500 dayly task fails but container does not get restarted

```sh
2024-11-22 01:17:30,775 [INFO ] web_scraper : remove_old_file: 115: The file Ogre-raw-data-report.txt does not exist in the current directory.
INFO:     172.21.0.4:43548 - "GET /run-task/ogre HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0xffff8236aac0>, 'Connection to www.ss.lv timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.ss.lv', port=443): Max retries exceeded with url: /lv/real-estate/flats/ogre-and-reg/ogre/sell/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8236aac0>, 'Connection to www.ss.lv timed out. (connect timeout=10)'))
```


Need to  prepare solution
