### ISSUE TITLE
BUG(ws): Traceback ValueError: 1 is not in range

### ISSUE THREAD

**Issue by vfedotovs** [vfedotovs/sslv_web_scraper#342]
web_scraper.py crashes due to additional tabs 

```py
2024-11-27 21:10:41,332 [INFO ] : split_price_column: 95: Started price column split
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 345, in get_loc
    return self._range.index(new_key)
ValueError: 1 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "df_cleaner.py", line 401, in <module>
    df_cleaner_main()
  File "df_cleaner.py", line 335, in df_cleaner_main
    clean_price_col = split_price_column(clean_sqm_col)
  File "df_cleaner.py", line 99, in split_price_column
    df_name["SQ_M_EUR"] = new[1]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 347, in get_loc
    raise KeyError(key) from err
KeyError: 1

```

**Comment by vfedotovs** [comment]
Resolved in [2449928](https://github.com/vfedotovs/sslv_web_scraper/pull/343/commits/2449928392163a31466ffc29445c8a5f79c63d0d)
